### ISSUE TITLE
360  安装APK 启动崩溃

### ISSUE THREAD

**Issue by ljackChen001** [pqpo/SmartCamera#1]
360  安装APK 启动崩溃

**Comment by pqpo** [comment]
日志麻烦贴一下

**Comment by ljackChen001** [comment]
没下载Demo  只下载了APK

**Comment by ljackChen001** [comment]
08-28 16:27:03.198 1008-1144/? E/InputDispatcher: channel '4036779 me.pqpo.smartcamera/me.pqpo.smartcamera.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by ljackChen001** [comment]
08-28 16:27:03.198 1008-1144/? E/InputDispatcher: channel '4036779 me.pqpo.smartcamera/me.pqpo.smartcamera.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-28 16:27:03.200 319-1111/? E/ImageEffectService: >>>>>>>>Unload all 0 plugins
08-28 16:27:03.204 319-3051/? E/CameraClient: >>>>>>>>>>>>>processdata_callback return
08-28 16:27:03.206 319-3051/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -32
08-28 16:27:03.206 319-3051/? E/MtkCam/DisplayClient: (3051)[enquePrvOps] mpStreamOps->enqueue_buffer failed: status[Broken pipe(32)], rpImgBuf(0xec5c26c8,0xe14b9000) (enquePrvOps){#426:vendor/mediatek/proprietary/hardware/mtkcam/legacy/v1/client/DisplayClient/DisplayClient.Stream.cpp}
08-28 16:27:03.403 319-1111/? E/CameraService: binderDied: Java client's binder died, removing it from the list of active clients
08-28 16:27:03.428 1008-2453/? E/PROXIMITY: PS batch: handle:7, en:0,samplingPeriodNs:200000000, maxBatchReportLatencyNs:0 
08-28 16:27:03.535 1008-1073/? E/MultiWindowProxy: getServiceInstance failed!
08-28 16:27:03.782 1008-1008/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 210 num clients 25
08-28 16:27:03.783 1008-1008/? E/WifiTrafficPoller:  packet count Tx=564603 Rx=1794957

**Comment by pqpo** [comment]
错误日志不在这段里面，麻烦看一下还有没有其他的错误信息。

**Comment by ljackChen001** [comment]
08-28 16:43:39.939 319-1165/? E/CameraServiceSniffer: YLLOG: skip do CameraServiceSniffer()
08-28 16:43:39.939 319-6714/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:OggS
    Cta5File::isCta5MultimediaFile false, bad magic:�q@
08-28 16:43:39.941 319-6716/? E/QkCommAVUtils: FileSource::isUseFileSourceProxy,is not local file
08-28 16:43:39.942 318-688/? E/DrmCtaPlugIn: [ERROR]onOpenDecryptSession - The key is not set by user
08-28 16:43:39.942 318-688/? E/DrmMtkUtil/DrmUtil: parseDcf: not dcf type, dcf version value [79]
08-28 16:43:39.942 318-688/? E/DrmMtkPlugIn: onOpenDecryptSession() : failed to parse dcf file.
08-28 16:43:39.947 319-6716/? E/APEExtractor: getAPEInfo not ape 5002
08-28 16:43:39.947 319-6716/? E/frameworks/av/media/libstagefright/libasf/src/parse.cpp: unknown object: 5367674f-200-0-0000000000003438, 0 bytes
08-28 16:43:39.947 319-6716/? E/frameworks/av/media/libstagefright/libasf/src/asf.cpp: error parsing header: -6
08-28 16:43:39.952 319-6714/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:OggS
08-28 16:43:39.952 319-6714/? E/Cta5File: Cta5File::isCta5MultimediaFile false, bad magic:r���HS�1��
08-28 16:43:39.953 319-6720/? E/QkCommAVUtils: FileSource::isUseFileSourceProxy,is not local file
08-28 16:43:39.954 318-7212/? E/DrmCtaPlugIn: [ERROR]onOpenDecryptSession - The key is not set by user
08-28 16:43:39.954 318-7212/? E/DrmMtkUtil/DrmUtil: parseDcf: not dcf type, dcf version value [79]
08-28 16:43:39.954 318-7212/? E/DrmMtkPlugIn: onOpenDecryptSession() : failed to parse dcf file.
08-28 16:43:39.958 319-6720/? E/APEExtractor: getAPEInfo not ape 5002
08-28 16:43:39.958 319-6720/? E/frameworks/av/media/libstagefright/libasf/src/parse.cpp: unknown object: 5367674f-200-0-000000000000245e, 34206 bytes
08-28 16:43:39.959 319-6720/? E/frameworks/av/media/libstagefright/libasf/src/asf.cpp: error parsing header: -6
08-28 16:43:39.989 319-1165/? E/af_mgr: [Hal3AInitState()] Err:   362:, m_pLaserDrv->init() fail 
08-28 16:43:40.013 319-1111/? E/MtkCam/Cam1Device:  NULL
    (1111)(Default:0)[setParameters] pszZsdMode is off (setParameters){#488:vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6735/v1/device/DefaultCam1Device.cpp}
08-28 16:43:40.020 319-1166/? E/MtkCam/CamAdapter:  NULL
08-28 16:43:40.023 319-1166/? E/MtkCam/CamAdapter:  NULL
08-28 16:43:40.057 319-1166/? E/ImgSensorDrv: [sendCommand]Err( 2063):[sendCommand] Err-ctrlCode (Success) 
08-28 16:43:40.057 319-1166/? E/MtkCam/HalSensor: [configure] CMD_SENSOR_GET_SENSOR_ROLLING_SHUTTER(10000)(3328) (configure){#1214:vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6735/hal/sensor/HalSensor.control.cpp}
08-28 16:43:40.063 319-6718/? E/aaa_sensor_mgr: [setSensorAWBGain()] Err:   864:, No Sensor object error
08-28 16:43:40.238 319-6718/? E/aaa_sensor_buf_mgr: [updateDMABaseAddr()] Err:   860:, u4BaseAddr is NULL
    [updateDMABaseAddr()] Err:   860:, u4BaseAddr is NULL
08-28 16:43:40.269 1008-1008/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 210 num clients 25
08-28 16:43:40.270 1008-1008/? E/WifiTrafficPoller:  packet count Tx=567915 Rx=1811625
    notifying of data activity 0
08-28 16:43:40.337 1026-1042/? E/MFI-Conn:  (     mfia_task_bootstrap,  587) mfia_task_bootstrap(): retrying to connect to mal-mfi error 13!! ====
08-28 16:43:40.418 319-1166/? E/MtkCam/Cam1Device:  NULL
08-28 16:43:40.576 319-319/? E/MtkCam/Cam1Device:  NULL
    (319)(Default:0)[setParameters] pszZsdMode is off (setParameters){#488:vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6735/v1/device/DefaultCam1Device.cpp}
08-28 16:43:40.578 1008-1154/? E/WifiConfigStore: updateConfiguration freq=2427 BSSID=d8:38:fc:28:ee:b8 RSSI=-47 "LINK-E"WPA_PSK
08-28 16:43:40.583 319-1166/? E/MtkCam/Cam1Device:  NULL
08-28 16:43:40.596 319-1166/? E/MtkCam/CamAdapter:  NULL
08-28 16:43:40.602 319-1166/? E/MtkCam/CamAdapter:  NULL
08-28 16:43:40.637 319-1166/? E/ImgSensorDrv: [sendCommand]Err( 2063):[sendCommand] Err-ctrlCode (Success) 
08-28 16:43:40.637 319-1166/? E/MtkCam/HalSensor: [configure] CMD_SENSOR_GET_SENSOR_ROLLING_SHUTTER(10000)(3328) (configure){#1214:vendor/mediatek/proprietary/hardware/mtkcam/legacy/platform/mt6735/hal/sensor/HalSensor.control.cpp}
08-28 16:43:40.642 319-6718/? E/aaa_sensor_mgr: [setSensorAWBGain()] Err:   864:, No Sensor object error
08-28 16:43:40.755 319-6718/? E/aaa_sensor_buf_mgr: [updateDMABaseAddr()] Err:   860:, u4BaseAddr is NULL
    [updateDMABaseAddr()] Err:   860:, u4BaseAddr is NULL
08-28 16:43:40.830 319-6718/? E/lsc_mgr2_rto_thread: [tsfBatch()] Err:   914:, [tsfBatch] Error(0x80000003): MTKTSF_FEATURE_BATCH
08-28 16:43:40.894 6670-6784/me.pqpo.smartcamera A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xf3780000 in tid 6784 (ScanThread)
08-28 16:43:40.894 6670-6686/me.pqpo.smartcamera A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xf378814c in tid 6686 (ScanThread)
08-28 16:43:40.896 6670-6787/me.pqpo.smartcamera A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xf37232ec in tid 6787 (ScanThread)
08-28 16:43:40.958 6789-6789/? E/AEE/AED: unexpected waitpid response: n=6784, status=0000000b
08-28 16:43:40.959 6789-6789/? E/AEE/AED: tid exited before attach completed: tid 6784
    request.action: 0
08-28 16:43:40.969 1008-1144/? E/InputDispatcher: channel 'bbc8af6 me.pqpo.smartcamera/me.pqpo.smartcamera.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-28 16:43:40.970 319-319/? E/ImageEffectService: >>>>>>>>Unload all 0 plugins
08-28 16:43:40.970 319-6762/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -32
08-28 16:43:40.970 319-6762/? E/MtkCam/DisplayClient: (6762)[enquePrvOps] mpStreamOps->enqueue_buffer failed: status[Broken pipe(32)], rpImgBuf(0xec5c2968,0xe2985000) (enquePrvOps){#426:vendor/mediatek/proprietary/hardware/mtkcam/legacy/v1/client/DisplayClient/DisplayClient.Stream.cpp}
08-28 16:43:40.990 1008-2473/? E/MultiWindowProxy: getServiceInstance failed!
08-28 16:43:41.212 319-319/? E/CameraService: binderDied: Java client's binder died, removing it from the list of active clients
08-28 16:43:41.272 1008-1008/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 210 num clients 25
     packet count Tx=567916 Rx=1811626
    notifying of data activity 3
08-28 16:43:41.337 1026-1042/? E/MFI-Conn:  (     mfia_task_bootstrap,  587) mfia_task_bootstrap(): retrying to connect to mal-mfi error 13!! ====
08-28 16:43:41.891 1008-1660/? E/PROXIMITY: PS batch: handle:7, en:0,samplingPeriodNs:200000000, maxBatchReportLatencyNs:0 
08-28 16:43:42.275 1008-1008/? E/WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 210 num clients 25
     packet count Tx=567916 Rx=1811627
    notifying of data activity 1

**Comment by pqpo** [comment]
see https://github.com/pqpo/SmartCamera/issues/14
