### ISSUE TITLE
使用的是 com.android.support:exifinterface ？

### ISSUE THREAD

**Issue by jinke1984** [pqpo/SmartCamera#13]
_Originally posted by @pqpo in https://github.com/pqpo/SmartCamera/issues/9#issuecomment-425627231_

**Comment by pqpo** [comment]
com.android.support:exifinterface 传入的 OutputStream 我看只支持 AssetManager.OutputStream 啊？你传入 ByteArrayOutputStream 可以的？
https://github.com/pqpo/SmartCamera/blob/master/smartcameralib/src/main/java/me/pqpo/smartcameralib/utils/BitmapUtil.java 这段代码来自于老版本的安卓源码，具体就是解析 Exif 格式的头信息读取旋转角度。

**Comment by jinke1984** [comment]
FormatTools.getInstance().Byte2InputStream(data)这个方法是将将byte转换成InputStream

**Comment by pqpo** [comment]
new ByteArrayInputStream(data); ?

**Comment by jinke1984** [comment]
嗯！是啊！

**Comment by pqpo** [comment]
好的，了解
