### ISSUE TITLE
竖屏比横屏的识别速度快很多，识别率高很多

### ISSUE THREAD

**Issue by bananaCaptain** [pqpo/SmartCamera#16]
你好！我在三星S7edge测试过 竖屏比横屏的识别速度快很多，识别率高很多，应该怎样设置 横屏的参数，还是可以再优化一下。
场景是身份证放在接近白色的黄色桌面上。
麻烦了

**Comment by bananaCaptain** [comment]
我发现不同设备识别率会不同！这个应该和摄像头的成像有关了！

**Comment by pqpo** [comment]
一般情况下固定竖屏或者横屏就行了，然后根据自己的场景调节参数。
你说 竖屏比横屏的识别速度快很多，是识别每一帧的速度快很多还是识别不出边框？

**Comment by bananaCaptain** [comment]
@pqpo 识别出框的速度，应该和硬件有些关系
