### ISSUE TITLE
小米 5s Plus miui8.0 在识别到框后会重新自动对焦才获取照片

### ISSUE THREAD

**Issue by bananaCaptain** [pqpo/SmartCamera#20]
小米 5s Plus miui8.0 在识别到框后会重新自动对焦才获取照片，结果是拿到的照片永远都是模糊的，请问有参数可以调整不？

**Comment by pqpo** [comment]
拍照的时候是会自动对焦的，需要等待一会再移开手机。
如果对拍摄的图像质量要求不是很高可以直接使用预览流中的图片。
在预览流的回调中使用 mCameraView.cropYuvImage 直接裁剪帧数据。
https://github.com/pqpo/SmartCamera/blob/master/app/src/main/java/me/pqpo/smartcamera/MainActivity.java#L140

**Comment by pqpo** [comment]
拍照的时候是会自动对焦的。如果对最终图片清晰度要求不是很高的话可以在预览流中直接裁剪出图片。
参考：
https://github.com/pqpo/SmartCamera/blob/master/app/src/main/java/me/pqpo/smartcamera/MainActivity.java#L140

**Comment by bananaCaptain** [comment]
感谢作者的帮忙！
