### ISSUE TITLE
在预览的时候调用 mCameraView.cropJpegImage 不能执行

### ISSUE THREAD

**Issue by bananaCaptain** [pqpo/SmartCamera#21]
mCameraView.setOnScanResultListener(new SmartCameraView.OnScanResultListener() {
            @Override
            public boolean onScanResult(SmartCameraView smartCameraView, int result, byte[] data) {
//                Bitmap previewBitmap = smartCameraView.getPreviewBitmap();
                if (result == 1) {
                    LogUtils.i("onScanResult()--->>>");
                    mCameraView.cropJpegImage  ....
                    return true;
                }
                return false;
            }
        });

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createBitmap(Bitmap.java:802)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:769)
        at me.pqpo.smartcameralib.SmartCameraView$2.run(SmartCameraView.java:168)

**Comment by pqpo** [comment]
使用 mCameraView.cropYuvImage 。
https://github.com/pqpo/SmartCamera/issues/20

**Comment by pqpo** [comment]
使用 mCameraView.cropYuvImage 。
https://github.com/pqpo/SmartCamera/issues/20
