### ISSUE TITLE
不支持魅族机型

### ISSUE THREAD

**Issue by BFELFISH** [pqpo/SmartCamera#22]
作者你好！我是在使用1.3.2的时候发现，魅族的机都会报这个错误
![image](https://user-images.githubusercontent.com/30564321/47946641-5404af80-df49-11e8-9475-7e6eddefd5f8.png)
目前只发现魅族会出错（魅族15，魅族pro6s和魅蓝metal）

**Comment by pqpo** [comment]
我的手机上有时候也会出现这个但是不会 crash，魅族手机会 crash ？

**Comment by BFELFISH** [comment]
>           我的手机上有时候也会出现这个但是不会 crash，魅族手机会 crash ？

嗯嗯，魅族手机的话，运行demo会闪退。
写在项目上运行时是扫描框上的那个扫描条会停住不动。不能拍照

**Comment by pqpo** [comment]
闪退的时候的报错就是这个，没其他错误日志了吗？

**Comment by BFELFISH** [comment]
>           是

我项目添加依赖是是添加的1.3.2的，然后其他机型没问题，魅族运行就会出现一开始那张图的错误

**Comment by 4what2do** [comment]
是的
魅族手机是不行

**Comment by forEveryDay** [comment]
我这边也是，昨天下载代码，魅族手机运行闪退，其它手机OK

**Comment by pqpo** [comment]
尝试使用最新版本：v2.0.0
