### ISSUE TITLE
TextureView doesn't support displaying a background drawable

### ISSUE THREAD

**Issue by GitHub-xiaomili** [pqpo/SmartCamera#27]
布局中尝试android:background="@null"
代码中添加@Override
public void setBackgroundDrawable(Drawable background) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N && background != null) {
        setBackgroundDrawable(background);
    }
}
建议作者在源码中添加上,不然引入依赖后再android 7.0 以上的机械上崩溃

**Comment by pqpo** [comment]
这种问题应该使用者自行兼容
