### ISSUE TITLE
SIMPLE: Error configuring

### ISSUE THREAD

**Issue by hVenus** [pqpo/SmartCamera#29]
Android 3.3.1
NDK 19.1.5304403
LLDB 3.1.4508709
Platform-tools 28.0.23
Gradle 4.4.
Android Plugin version 3.1.4

我要怎么做？

您这两个项目我都没运行起来。

还有,你这个库我要怎么引用到自己的项目里？能简单说下吗？
单独导入您的lib module不行，试过了。

**Comment by mordot** [comment]
注释掉build.gradle中的CMakeLists.txt配置就可以通过编译，但CMakeLists.txt文件怎么看都没问题，cmake版本问题？

**Comment by wlx10011101** [comment]
遇到同样的问题，好像Cmake的错误日志Gradle取不出，直接看下gradle日志，找到Cmake的error

**Comment by pqpo** [comment]
降低 NDK 版本
