### ISSUE TITLE
不同模板能否提供方法传入呢

### ISSUE THREAD

**Issue by zhuyingying123** [pqpo/SmartCamera#32]
模板不同，都得自定义模板吗？有点麻烦，能否直接传对应的图片或者bitmap的方法提供呢？

**Comment by pqpo** [comment]
不太明白，模板是指？

**Comment by helloworkcupid** [comment]
他说的模板，应该和我想的一样，比如说 把采集区域设置成圆形，或者 其他形状。
也许他的意思是要识别的对象的模板吧，我是想把采集区域设置成圆形。作者用了RectF 矩形类，应该是不能实现的吧

**Comment by pqpo** [comment]
暂不支持
