### ISSUE TITLE
AndroidQ打开相机出现异常

### ISSUE THREAD

**Issue by JoinBelieve** [pqpo/SmartCamera#39]
作者你好，这是我遇到得异常。
异常信息：java.lang.RuntimeException: java.io.IOException: setPreviewTexture failed
手机型号：pixel one
系统版本：AndroidQ

**Comment by pqpo** [comment]
用华为 Android Q 的手机试了一下没出现异常，不好复现，异常信息有些少。
是 Demo apk 还是自己集成之后报错的？有没有给权限？

**Comment by TheorayVic** [comment]
大神您好、我在公众号给您留言了、麻烦回复一下、感谢

**Comment by JoinBelieve** [comment]
抱歉抱歉，这时候才看到，问题已经解决了，我重启了手机。
谢谢 @pqpo
