### ISSUE TITLE
有没有办法让识别的图片尽可能的完美不留白边

### ISSUE THREAD

**Issue by qq724418408** [pqpo/SmartCamera#48]
需要调整哪些参数可以让识别的证件能尽可能的不出现白边呢？

**Comment by qq724418408** [comment]
SmartScanner.cannyThreshold1 = 20;
        SmartScanner.cannyThreshold2 = 50;
        SmartScanner.houghLinesThreshold = 130;
        SmartScanner.houghLinesMinLineLength = 80;
        SmartScanner.houghLinesMaxLineGap = 10;
        SmartScanner.gaussianBlurRadius = 3;
        SmartScanner.detectionRatio = 0.05f;
        SmartScanner.checkMinLengthRatio = 0.5f;
        SmartScanner.maxSize = 300;
        SmartScanner.angleThreshold = 5;

**Comment by qq724418408** [comment]
当前的参数设置如上↑

**Comment by pqpo** [comment]
SmartScanner.detectionRatio = 0.05f;
识别区域，变小可以减少白边，但是也更难识别了。

**Comment by qq724418408** [comment]
可不可以提供回调返回图片的四个角坐标呢

**Comment by qq724418408** [comment]
SmartScanner.detectionRatio = 0.05f;
这个取值最小能取到多少呢？
