### ISSUE TITLE
裁剪出来的图片不是扫码框内的部分，无法正确演示效果

### ISSUE THREAD

**Issue by bananaCaptain** [pqpo/SmartCamera#8]
作者你好：demo裁剪出来的图片不是扫码框内的部分 是不是以下代码需要对原始数据进行方向判断并转换方向？麻烦了
 @Override
            public void onPictureTaken(CameraView cameraView, byte[] data) {
                super.onPictureTaken(cameraView, data);
                //TODO data的方向与预览的不一致
                mCameraView.cropImage(data, new SmartCameraView.CropCallback() {
                    @Override
                    public void onCropped(Bitmap cropBitmap) {
                        if (cropBitmap != null) {
                            showPicture(cropBitmap);
                        }
                    }
                });
            }

**Comment by pqpo** [comment]
扫描预览是正常的？就拍照裁剪不正常？手机是关闭屏幕旋转还是开启状态？

CameraView.cropImage 里面已经做过方向判断了。
